type UserSession
  @auth(
    rules: [
      { allow: owner }
      { allow: roles, roles: ["Admin"] }
      { allow: permissions, permissions: ["ReadUserSession"] }
    ]
  ) {
  id: ID!
  jti: ID!
  clientId: ID!
  clientIp: IP!
  createdAt: DateTime!
  userAgent: String
  user: User!
}

type Query {
  session(id: ID!): UserSession!
    @auth(
      rules: [
        { allow: roles, roles: ["Admin"] }
        { allow: permissions, permissions: ["ReadUserSession"] }
      ]
    )

  sessions(limit: Int): SessionsList!
    @auth(
      rules: [
        { allow: roles, roles: ["Admin"] }
        { allow: permissions, permissions: ["ReadUserSession"] }
      ]
    )
}

type Mutation {
  deleteUserSessions(inputs: [DeleteUserSessionInput!]!): [UserSession]!
    @auth(
      rules: [
        { allow: roles, roles: ["Admin"] }
        { allow: permissions, permissions: ["DeleteUserSession"] }
      ]
    )
}

type SessionsList {
  items: [UserSession]!
}

input DeleteUserSessionInput {
  id: ID!
}
